import PageNav from '../../components/PageNav'

export default function Overview() {
  return (
    <>
      <div className="page-header">
        <div className="page-header-breadcrumb">Getting Started</div>
        <h1>Overview</h1>
      </div>

      <div className="doc-content">
        <h2>What Is DexDuel</h2>
        <p>
          DexDuel is a fully on-chain, <strong>lossless prediction game</strong> built on <strong>OneChain</strong> — a high-performance Sui VM-compatible blockchain.
          Players predict whether a crypto asset's price will go <strong>UP</strong> or <strong>DOWN</strong> within a tournament window, competing for yield-based rewards while keeping their full stake intact.
        </p>
        <p>
          Unlike traditional prediction markets where losing means forfeiting your stake, DexDuel runs on a <strong>no-loss model</strong>.
          Every participant gets their original entry fee back after each round. Only the yield generated by the pooled stakes is distributed as prizes to top performers.
        </p>

        <h2>Why OneChain Is DexDuel's Home Chain</h2>

        <h3>Built on Sui VM Architecture</h3>
        <p>
          DexDuel's smart contracts are written in <strong>Move</strong>, a resource-oriented programming language designed for safe and verifiable on-chain computation.
          Move's strict ownership model and type safety eliminate entire classes of smart contract vulnerabilities, making it ideal for financial applications.
        </p>
        <p>Key advantages of Move on OneChain:</p>
        <ul>
          <li><strong>Resource safety</strong> — assets cannot be duplicated or accidentally destroyed</li>
          <li><strong>Strong type system</strong> — compile-time guarantees prevent runtime errors</li>
          <li><strong>Modular architecture</strong> — composable contract design enables clean separation of concerns</li>
          <li><strong>Native object model</strong> — shared objects provide efficient concurrent access for multi-player games</li>
        </ul>

        <h3>Game State Anchored On-Chain</h3>
        <p>All game state is stored and executed directly on OneChain. This includes:</p>
        <ul>
          <li>Tournament sessions and round configurations</li>
          <li>Player predictions and stakes</li>
          <li>Leaderboard rankings and scoring</li>
          <li>Reward distribution and settlement</li>
        </ul>
        <p>
          By anchoring all state on-chain, DexDuel ensures complete transparency, verifiability, and trustlessness — no off-chain database or centralized server controls the game outcome.
        </p>

        <h3>Low-Latency Execution for Real-Time Gaming</h3>
        <p>OneChain provides the performance characteristics required for a responsive gaming experience:</p>
        <ul>
          <li><strong>Sub-second finality</strong> — predictions are confirmed almost instantly</li>
          <li><strong>Low transaction costs</strong> — affordable entry for all players</li>
          <li><strong>High throughput</strong> — supports concurrent tournaments with many participants</li>
          <li><strong>Reliable uptime</strong> — consistent availability for time-sensitive game rounds</li>
        </ul>

        <h2>What DexDuel Unlocks</h2>

        <h3>Lossless Prediction Gaming</h3>
        <p>DexDuel introduces a paradigm where players can:</p>
        <ol>
          <li>Stake USDT to enter a prediction tournament</li>
          <li>Predict whether a crypto asset's price will go UP or DOWN</li>
          <li>Win yield-based rewards if their prediction is correct</li>
          <li><strong>Always receive their original stake back</strong> — win or lose</li>
        </ol>
        <p>No fear of loss. No financial barrier to entry.</p>

        <h3>Cross-Chain Yield Generation</h3>
        <p>
          DexDuel integrates a <strong>cross-chain EVM Vault</strong> on Base to generate real yield from pooled stakes.
          A relayer bridge between OneChain and Base handles the flow:
        </p>
        <ul>
          <li>Entry fees are mirrored to the EVM Vault</li>
          <li>Yield is generated through DeFi protocols (Aave V3 integration planned)</li>
          <li>Prizes come from real yield — not from other players' losses</li>
        </ul>

        <h3>Competitive Ranking with Season Progression</h3>
        <p>DexDuel features a comprehensive scoring and leaderboard system that rewards consistent performance:</p>
        <ul>
          <li><strong>Win points</strong> for correct predictions</li>
          <li><strong>Streak bonuses</strong> for consecutive wins</li>
          <li><strong>Early prediction bonuses</strong> for decisive players</li>
          <li><strong>Season-based rankings</strong> for long-term competition</li>
        </ul>
      </div>

      <PageNav currentPath="/getting-started/overview" />
    </>
  )
}
